Design and layout cleanup
MAKENTNU/web pull request #338
Opened 2021-02-18 12:38 UTC by ddabble

### Highlights:
* Fixed weird scaling and small font sizes on mobile (c2322d7be2ddab5ea1c054b19153d297ab7f8801) and fixed some related sizing and layout issues (a1998f885858e2d4b485bc27fbc34b354b23eca0)
* Made the Ubuntu font apply everywhere (54f6ac42debc3ea69f48fa9370a46a14081a5b5a)
* Made the usage of the colors of MAKE's graphic charter consistent (5b7dcc378943c905c818031e8b3355a0b5ae8fc5)
* Improved design of committee and equipment admin (e98ff98d7cedbeaade2253fccd8fb5925552cb8f)
* Made the usage of edit/save/cancel buttons consistent (1fc65d9a17d550510f5f155eda1cb1ae3d9ed13b)

### Also, code improvements and bug fixes:
* Huge cleanup of various whitespace, which includes cleaning up *actual* whitespace, but is mostly rearrangement of code (that doesn't alter the function in any way) (412e53f9af6e51bc4b9b075bf2986b59283d6136)
* Added missing priority field to machine edit form (329355c3c83614df85814eb8b78e0fd0c055b01a)
* Fixed `CategoryAdmin` missing from Django admin (52e72fe93059d5f588cab8c24348e077d9220387)

2021-02-19 09:35 UTC, Maisergodt requested changes
Nice!
I left some feedback :)

2021-03-05 12:09 UTC, ddabble commented on make_queue/models/models.py
>      showed = models.NullBooleanField(default=None)
Yes, it should 😄 I have a fix for it ready in an upcoming PR 🙂

2021-03-05 12:14 UTC, ddabble commented on faq/models.py
> +    name = MultiLingualTextField(unique=True, verbose_name=_('Category'))
I agree, though I'm unsure whether this change (and similar changes elsewhere in the codebase) fits this PR.. 🤔 Also I have the same fix ready for an(other) upcoming PR 😁

2021-03-05 12:21 UTC, ddabble commented on internal/templates/internal/header.html
> +            <div class="make-bg-blue bubble-background"></div>
I personally think the current color pattern is better than any randomized pattern 😅 There exists a [card on Trello](https://trello.com/c/WMEziJ6E/182-add-an-admin-panel-for-editing-the-header-buttons) that details adding an admin panel for changing the colors of these buttons - among other things. Changing any of this, however, is kind of not within the scope of this PR, in my opinion.. Do you agree? 🙂

2021-03-06 22:11 UTC, Maisergodt commented on internal/templates/internal/header.html
> +            <div class="make-bg-blue bubble-background"></div>
I wasn't aware of that card, then nevermind my comment 😛

2021-03-08 00:34 UTC, ddabble commented on news/templates/news/admin_event_ticket_list.html
>              <button class="copy-token"><i class="clipboard icon"></i></button>
Yes, good idea! 💯

2021-03-08 00:37 UTC, ddabble commented
@Maisergodt I improved the design of the button for copying the email addresses of event ticket holders, as you suggested 😊

2021-03-08 08:40 UTC, sigtheidiot approved these changes

2021-03-08 12:35 UTC, Maisergodt approved these changes

2021-03-08 13:07 UTC, merged