Add code style guide + guideline for code smells
MAKENTNU/web pull request #376
Opened 2021-09-16 16:54 UTC by ddabble

2021-09-16 19:13 UTC, mahoyen requested changes
Great work! It is nice to have something to look up when you are unsure on how to do things. 

I only have two comments/clarifications.

2021-09-18 15:58 UTC, ddabble commented on CONTRIBUTING.md
> +    ]
This specific section of the style guide is actually only about where to place the *operator* when wrapping, and not whether to place operands on the same or a new line after opening brackets 😅 Other than that, this style guide does not enforce any further details on how to wrap lines with regards to bracket placement 🙂 (Admittedly, I can mention that I purposefully included a variety of (good/acceptable) examples of how one can wrap lines, in this example snippet 🤠 None of them based themselves on the whether the expression was boolean or a list comprehension or whatnot, though 😅)

2021-09-18 16:02 UTC, ddabble commented on CONTRIBUTING.md
> +`<a>` tags leading the user away from the "flow" of the current page, should always have its `target` attribute set to `"_blank"`.
Yes, nice suggestion! 😄

2021-09-24 19:04 UTC, mahoyen commented on CONTRIBUTING.md
> +    ]
ok :)

2021-09-24 20:06 UTC, mahoyen approved these changes
I have updated my own PR after the most recent change :P

2021-09-24 20:09 UTC, ddabble commented
Nice! 😄 I'll review it when I have the time; sorry for the long wait! 😬

2021-09-24 20:09 UTC, merged